project:
  type: website

website:
  title: "Dawie Griesel"
  # site-url: 
  description: "Dawie's personal blog about R and Shiny"
  navbar:
    right:
      - text: Blog
      - href: blog.qmd
      - icon: github
        href: https://github.com/dawiegriesel
      - icon: twitter
        href: https://twitter.com
  cookie-consent: true

# filters: 
#   - code-filename

format:
  html:
    theme: theme.scss
    css: styles.css
